/*
Copyright 2026 Benny Powers. All rights reserved.
Use of this source code is governed by the GPLv3
license that can be found in the LICENSE file.
*/

// Package tailwind provides Tailwind CSS theme configuration formatting for design tokens.
package tailwind

import (
	"encoding/json"
	"strings"

	"bennypowers.dev/asimonim/convert/formatter"
	"bennypowers.dev/asimonim/token"
)

// Formatter outputs Tailwind theme configuration.
type Formatter struct{}

// New creates a new Tailwind formatter.
func New() *Formatter {
	return &Formatter{}
}

// Format converts tokens to Tailwind theme configuration.
// Note: prefix is not applied to Tailwind output as it uses its own structure.
func (f *Formatter) Format(tokens []*token.Token, _ formatter.Options) ([]byte, error) {
	theme := make(map[string]any)

	for _, tok := range tokens {
		if len(tok.Path) == 0 {
			continue
		}

		themeKey := mapToTailwindKey(tok.Type, tok.Path[0])
		if themeKey == "" {
			continue
		}

		if _, exists := theme[themeKey]; !exists {
			theme[themeKey] = make(map[string]any)
		}

		var keyPath []string
		if len(tok.Path) > 1 {
			keyPath = tok.Path[1:]
		} else {
			keyPath = []string{"DEFAULT"}
		}

		current, ok := theme[themeKey].(map[string]any)
		if !ok {
			current = make(map[string]any)
			theme[themeKey] = current
		}
		for i, segment := range keyPath {
			if i == len(keyPath)-1 {
				current[segment] = formatter.ResolvedValue(tok)
			} else {
				next, ok := current[segment].(map[string]any)
				if !ok {
					next = make(map[string]any)
					current[segment] = next
				}
				current = next
			}
		}
	}

	result := map[string]any{
		"theme": map[string]any{
			"extend": theme,
		},
	}

	output, err := json.MarshalIndent(result, "", "  ")
	if err != nil {
		return nil, err
	}

	var sb strings.Builder
	sb.WriteString("// Generated by asimonim\n")
	sb.WriteString("// Do not edit manually\n\n")
	sb.WriteString("/** @type {import('tailwindcss').Config} */\n")
	sb.WriteString("module.exports = ")
	sb.Write(output)
	sb.WriteString(";\n")

	return []byte(sb.String()), nil
}

func mapToTailwindKey(tokenType, pathFirst string) string {
	switch tokenType {
	case token.TypeColor:
		return "colors"
	case token.TypeDimension:
		switch pathFirst {
		case "spacing", "space", "gap":
			return "spacing"
		case "radius", "borderRadius":
			return "borderRadius"
		case "fontSize", "font-size":
			return "fontSize"
		case "lineHeight", "line-height":
			return "lineHeight"
		case "borderWidth", "border-width":
			return "borderWidth"
		default:
			return "spacing"
		}
	case token.TypeFontFamily:
		return "fontFamily"
	case token.TypeFontWeight:
		return "fontWeight"
	case token.TypeDuration:
		return "transitionDuration"
	case token.TypeCubicBezier:
		return "transitionTimingFunction"
	case token.TypeShadow:
		return "boxShadow"
	}

	switch pathFirst {
	case "color", "colors":
		return "colors"
	case "spacing", "space":
		return "spacing"
	case "font", "typography":
		return "fontSize"
	default:
		return ""
	}
}
