// Generated by asimonim
// Do not edit manually

/**
 * Represents a color value in DTCG 2025.10 format.
 * @see https://design-tokens.github.io/community-group/format/#color
 */
export interface Color {
  colorSpace: string;
  components: (number | "none")[];
  alpha?: number;
  hex?: string;
}

/**
 * Represents a dimension value with numeric value and unit.
 */
export interface Dimension {
  value: number;
  unit: string;
}

/**
 * Represents a design token with its value and metadata.
 */
export interface DesignToken<V> {
  $value: V;
  $type?: string;
  $description?: string;
}

/**
 * Union type of all token names (CSS variable or dot-path).
 */
export type TokenName =
  | "--color-primary"
  | "color.primary"
  | "--spacing-small"
  | "spacing.small";

/**
 * Typed map for accessing design tokens by CSS variable name or dot-path.
 */
export class TokenMap<T extends Record<string, DesignToken<unknown>>> {
  #map: Map<string, DesignToken<unknown>>;

  get size(): number { return this.#map.size; }
  [Symbol.iterator]() { return this.#map[Symbol.iterator](); }

  constructor(
    entries: T,
    prefix = "",
    delimiter = "-"
  ) {
    this.#map = new Map(Object.entries(entries));
    // Add dot-path aliases
    for (const [key, value] of this.#map) {
      if (key.startsWith("--")) {
        let path = key.slice(2);
        if (prefix && path.startsWith(prefix + delimiter)) {
          path = path.slice(prefix.length + delimiter.length);
        }
        const dotPath = path.split(delimiter).join(".");
        this.#map.set(dotPath, value);
      }
    }
  }

  get<K extends keyof T>(name: K): T[K];
  get(name: string): DesignToken<unknown> | undefined;
  get(name: string): DesignToken<unknown> | undefined {
    return this.#map.get(name);
  }

  has<K extends keyof T>(name: K): true;
  has(name: string): boolean;
  has(name: string): boolean { return this.#map.has(name); }

  keys() { return this.#map.keys(); }
  values() { return this.#map.values(); }
  entries() { return this.#map.entries(); }
  forEach(fn: (value: DesignToken<unknown>, key: string, map: TokenMap<T>) => void, thisArg?: unknown): void {
    this.#map.forEach((v, k) => { fn.call(thisArg, v, k, this); });
  }
}

/**
 * Default token map instance.
 */
export const tokens = new TokenMap({
  "--color-primary": {
      "$description": "Primary brand color",
      "$type": "color",
      "$value": "#FF6B35"
    } as DesignToken<Color>,
  "--spacing-small": {
      "$type": "dimension",
      "$value": "4px"
    } as DesignToken<string>,
}, "", "-");
