// Generated by asimonim
// Do not edit manually

/**
 * Represents a color value in DTCG 2025.10 format.
 * @see https://design-tokens.github.io/community-group/format/#color
 */
export interface Color {
  colorSpace: string;
  components: (number | "none")[];
  alpha?: number;
  hex?: string;
}

/**
 * Represents a dimension value with numeric value and unit.
 */
export interface Dimension {
  value: number;
  unit: string;
}

/**
 * Represents a design token with its value and metadata.
 */
export interface DesignToken<V> {
  $value: V;
  $type?: string;
  $description?: string;
}

/**
 * Union type of all token names (CSS variable or dot-path).
 */
export type TokenName = never;

/**
 * Typed map for accessing design tokens by CSS variable name or dot-path.
 */
class TokenMap {
  #map: Map<TokenName, DesignToken<unknown>>;

  get size(): number { return this.#map.size; }
  [Symbol.iterator]() { return this.#map[Symbol.iterator](); }

  constructor(
    entries: Record<string, DesignToken<unknown>>,
    prefix = "",
    delimiter = "-"
  ) {
    this.#map = new Map(Object.entries(entries)) as Map<TokenName, DesignToken<unknown>>;
    // Add dot-path aliases
    for (const [key, value] of this.#map) {
      if (key.startsWith("--")) {
        let path = key.slice(2);
        if (prefix && path.startsWith(prefix + delimiter)) {
          path = path.slice(prefix.length + delimiter.length);
        }
        const dotPath = path.split(delimiter).join(".");
        this.#map.set(dotPath as TokenName, value);
      }
    }
  }

  get(name: TokenName): DesignToken<unknown>;
  get(name: string): undefined;
  get(name: TokenName): DesignToken<unknown> | undefined {
    return this.#map.get(name as TokenName);
  }

  has(name: TokenName): true;
  has(name: string): false;
  has(name: string): boolean { return this.#map.has(name as TokenName); }

  keys() { return this.#map.keys(); }
  values() { return this.#map.values(); }
  entries() { return this.#map.entries(); }
  forEach(fn: (value: DesignToken<unknown>, key: TokenName, map: TokenMap) => void, thisArg?: unknown): void {
    this.#map.forEach((v, k) => { fn.call(thisArg, v, k, this); });
  }
}

/**
 * Default token map instance.
 */
export const tokens = new TokenMap({
}, "", "-");
