/*
Copyright 2026 Benny Powers. All rights reserved.
Use of this source code is governed by the GPLv3
license that can be found in the LICENSE file.
*/

// Package cts provides TypeScript CommonJS formatting for design tokens.
package cts

import (
	"fmt"
	"strings"

	"bennypowers.dev/asimonim/convert/formatter"
	"bennypowers.dev/asimonim/convert/formatter/typescript"
	"bennypowers.dev/asimonim/token"
)

// Formatter outputs TypeScript CommonJS with camelCase exports.
type Formatter struct{}

// New creates a new CTS formatter.
func New() *Formatter {
	return &Formatter{}
}

// Format converts tokens to TypeScript CommonJS format.
func (f *Formatter) Format(tokens []*token.Token, opts formatter.Options) ([]byte, error) {
	var sb strings.Builder

	// Add header if provided, otherwise use default
	if opts.Header != "" {
		sb.WriteString(formatter.FormatHeader(opts.Header, formatter.CStyleComments))
	} else {
		sb.WriteString("// Generated by asimonim\n")
		sb.WriteString("// Do not edit manually\n\n")
	}

	sorted := formatter.SortTokens(tokens)

	for _, tok := range sorted {
		baseName := formatter.ToCamelCase(strings.Join(tok.Path, "-"))
		name := formatter.ApplyPrefixCamel(baseName, opts.Prefix)
		value := formatter.ResolvedValue(tok)
		tsValue := typescript.ToValue(value)

		if tok.Description != "" {
			sb.WriteString(typescript.FormatJSDoc(tok.Description))
		}
		sb.WriteString(fmt.Sprintf("exports.%s = %s as const;\n", name, tsValue))
	}

	return []byte(sb.String()), nil
}
