// Generated by asimonim
// Do not edit manually

import Foundation
import SwiftUI

public enum DesignTokens {

    // MARK: - Font Weight
    public enum FontWeight {
        public static let fontWeightBold = 700
        public static let fontWeightLight = 300
    }

    // MARK: - Number
    public enum NumberTokens {
        public static let sizeInteger = 42
        public static let sizeScale = 1.5
    }
}
