// Generated by asimonim
// Do not edit manually

import Foundation
import SwiftUI

public enum DesignTokens {

    // MARK: - String
    public enum StringTokens {
        public static let labelGreeting = "Hello World"
    }
}
