// Generated by asimonim
// Do not edit manually

/** Primary brand color */
export const colorPrimary = "#FF6B35" as const;
export const colorSecondary = "#004E64" as const;
export const spacingMedium = "8px" as const;
export const spacingSmall = "4px" as const;
